### ISSUE TITLE
[Install error] cannot stat 'sleighc': No such file or directory

### ISSUE THREAD

**Issue by ayedaemon** [radareorg/r2ghidra#101]
I'm trying to install this plugin via `r2pm` but I'm this error (as in below screenshot)

![image](https://user-images.githubusercontent.com/39592651/202743424-98a69408-cd7c-41ac-adf0-d8445a6d6d70.png)

Commands used to install:-

```
r2pm -U
r2pm -ci r2ghidra
```

---
I'm on `6.0.6-arch1-1` with radare2 installed via github (not by package manager).

```
5.7.8-551-gf05b4e2eba  r2
5.7.8-551-gf05b4e2eba  r_anal
5.7.8-551-gf05b4e2eba  r_lib
5.7.8-551-gf05b4e2eba  r_egg
5.7.8-551-gf05b4e2eba  r_asm
5.7.8-551-gf05b4e2eba  r_bin
5.7.8-551-gf05b4e2eba  r_cons
5.7.8-551-gf05b4e2eba  r_flag
5.7.8-551-gf05b4e2eba  r_core
5.7.8-551-gf05b4e2eba  r_crypto
5.7.8-551-gf05b4e2eba  r_bp
5.7.8-551-gf05b4e2eba  r_debug
5.7.8-551-gf05b4e2eba  r_main
5.7.8-551-gf05b4e2eba  r_fs
5.7.8-551-gf05b4e2eba  r_io
5.7.8-551-gf05b4e2eba  r_magic
5.7.8-551-gf05b4e2eba  r_parse
5.7.8-551-gf05b4e2eba  r_reg
5.7.8-551-gf05b4e2eba  r_sign
5.7.8-551-gf05b4e2eba  r_search
5.7.8-551-gf05b4e2eba  r_syscall
5.7.8-551-gf05b4e2eba  r_util
```

**Comment by trufae** [comment]
looks like you are neither using last release or last git, so build errors are expected

**Comment by ayedaemon** [comment]
I updated the tool via `sys/install.sh` script from the base repo, it got updated to `5.7.8-569-gddda012afc` and now works as expected. I'm sure I did that before creating the issue though. 

Thanks for the help and this amazing tool :)
