### ISSUE TITLE
add the boolean check kwarg to the run_command call

### ISSUE THREAD

**Issue by milahu** [radareorg/r2ghidra#110]
add check:false to run_command

https://github.com/radareorg/r2ghidra/blob/0799403b8ae3c2a09a176f1312825619912185e3/meson.build#L35-L41

> WARNING: You should add the boolean check kwarg to the run_command call.
> It currently defaults to false,
> but it will default to true in future releases of meson.
> See also: https://github.com/mesonbuild/meson/issues/9300

**Comment by trufae** [comment]
Can you send a pullreq instead of explaining what to do?
