### ISSUE TITLE
How to install on Kali?

### ISSUE THREAD

**Issue by Network-Sec** [radareorg/r2ghidra#113]
Latest 5.8.2 deb fails to install with dpkg 
Using 5.8.0 deb does install but I still get 
"radare2/rizin plugin r2ghidra/rzghidra must be installed and available from r2/rz"

Installing r2pipe via pip3 doesn't help.

In r2 it's not available and suggests to do "r2pm -ci r2ghidra"
When I do that, I get a compile error "anal_ghidra_plugin.c:28:10: error: ‘RAnalPlugin’ {aka ‘struct r_anal_plugin_t’} has no member named ‘cpus’"

I depend on this plugin but for the last 2 years I had to fallback to an older Ubuntu 18.04 where the installation worked. Please update instructions. Thanks for your hard work, it's amazing!

**Comment by trufae** [comment]
- the deb fails to install -> why? Whats the error?
- I dont get whats this r2/rz thing or what do you mean with this
- Having this compile error probably means that you have an ancient installation of r2 in the system and you need to remove the old package and purge it with dpkg --purge or so
- Its normal that the deb pkg doesnt works on ubuntu 18 because the debian packages are compiled on ubuntu lts and ubuntu18 was removed from the continuous integration of github

**Comment by roldugin** [comment]
@trufae is right, the version of `radare2` bundled with Kali 2023.1 is too old. `radare2` 5.5.0 was released on Nov 15, 2021. See all versions [here](https://github.com/radareorg/radare2/tags).

```sh
# Uninstall Kali's default version of radare2
dpkg -l | grep radare
ii  libradare2-5.0.0:arm64                        5.5.0+dfsg-1+b1                      arm64        libraries from the radare2 suite
ii  libradare2-common                             5.5.0+dfsg-1                         all          arch independent files from the radare2 suite
ii  libradare2-dev                                5.5.0+dfsg-1+b1                      arm64        devel files from the radare2 suite
ii  radare2                                       5.5.0+dfsg-1+b1                      arm64        free and advanced command line hexadecimal editor

sudo apt remove radare2 libradare2-dev libradare2-common libradare2-5.0.0

# Follow official instructions to install latest radare2: https://github.com/radareorg/radare2#installation
git clone https://github.com/radareorg/radare2
radare2/sys/install.sh

# Follow official instructions to install r2ghidra: https://github.com/radareorg/r2ghidra#installing
r2pm update
r2pm -ci r2ghidra
```

**Comment by radare** [comment]
Closing the ticket

**Comment by radare** [comment]
Thanks for confirming and sharing the versions shipped in kali
