### ISSUE TITLE
compiling under windows

### ISSUE THREAD

**Issue by q8ing** [radareorg/r2ghidra#12]
hello,

I tried to compile it for windows, but I faced an error:

![1](https://user-images.githubusercontent.com/52950756/106823042-48a50f00-6691-11eb-8f47-4952385b44ec.png)

My cmake version is:
------
C:\Users\root\Desktop\r2ghidra\build>cmake -version
cmake version 3.19.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

---------

I am using the latest radare2 version and It works perfectly.

-----
C:\Users\root\Desktop\r2ghidra\build>radare2 -v
radare2 5.1.0 25703 @ windows-x86-64 git.5.1.0-28-g89ff9aaf6
commit: 89ff9aaf6e668dfd2a17bf4cd9a1bdd7e176f4bd build: Wed 02/03/2021__ 7:29:32.24
-------

--------
C:\Users\root\Desktop\r2ghidra\build>radare2 -H
R2_VERSION=5.1.0
R2_PREFIX=.
R2_MAGICPATH=C:\Users\root\AppData\Local\Programs\radare2\dist\share\magic
R2_INCDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\include\libr
R2_LIBDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\lib
R2_LIBEXT=dll
R2_RCONFIGHOME=C:\Users\root\.config\radare2
R2_RDATAHOME=C:\Users\root\.local\share\radare2
R2_RCACHEHOME=C:\Users\root\.cache\radare2
R2_LIBR_PLUGINS=C:\Users\root\AppData\Local\Programs\radare2\dist\lib\plugins
R2_USER_PLUGINS=C:\Users\root\.local\share\radare2\plugins
R2_USER_ZIGNS=C:\Users\root\.local\share\radare2\zigns
--------

Any help is appreciated.

**Comment by sab24** [comment]
Hi, I fixed this in a push request, it just takes some time before this will be merged into master

**Comment by q8ing** [comment]
> Hi, I fixed this in a push request, it just takes some time before this will be merged into master

Thank you, friend :>

**Comment by sab24** [comment]
Hi Q8ing, in the meantime you can try my fork, see if it compiles for you and you can get the plugin working on your system
https://github.com/sab24/r2ghidra

**Comment by trufae** [comment]
@sab24 can you please submit PRs with the fixes of your fork?

**Comment by trufae** [comment]
i think all the relevant fixes of your branch are already in here. about changing the code style. i think it's better to stick to the current one to ease taking patches from rz-ghidra and follow the ghidra c++ style for consistency. Despite i totally dislike that indentation.

**Comment by sab24** [comment]
Hi Pancake,

This is already merged into master by PR #17 . I think this issue can be closed

**Comment by trufae** [comment]
Cool! Thank you!
