### ISSUE TITLE
Error installing r2ghidra with r2pm

### ISSUE THREAD

**Issue by mahidsec** [radareorg/r2ghidra#127]
**Error Look like this**
```
Using PKGCONFIG: /usr/bin/pkg-config
checking pkg-config flags for r_core... no
This package is required
gmake: *** No rule to make target 'ghidra-native'.  Stop.
```

**Comment by trufae** [comment]
How did you installed radare2? Which os? Do you have pkgconfig installed?

**Comment by mahidsec** [comment]
Installed from github repo and it is on Kali linux version 2024.1 .  yes, a quick search shows 
```
$ whereis pkgconfig
pkgconfig: /usr/lib/x86_64-linux-gnu/pkgconfig /usr/lib/pkgconfig /usr/local/lib/pkgconfig /usr/share/pkgconfig
```

**Comment by trufae** [comment]
How did you installed radare2?

**Comment by trufae** [comment]
Because pkgconfig should be able to find the library otherwise theres something wrong in your system

**Comment by mahidsec** [comment]
> How did you installed radare2?

I cloned it from github and run the sys/install.sh

**Comment by mahidsec** [comment]
> Because pkgconfig should be able to find the library otherwise theres something wrong in your system

I've reinstalled radare2 multiple times but it seems nothing happened.

**Comment by mahidsec** [comment]
## Status: Fixed

### After trying to reinstall the r2 it seems like the problem is fixed! Thanks
