### ISSUE TITLE
Install erro on Ubuntu18.04 

### ISSUE THREAD

**Issue by fzmili** [radareorg/r2ghidra#129]
## Description
I install radare2  under the Official Step:
```
git clone https://github.com/radareorg/radare2
radare2/sys/install.sh
```
However, when I installed the plugin r2ghidra, an error occurred. As shown in the figure below
![image](https://github.com/radareorg/r2ghidra/assets/39305487/7602d907-be3d-47e6-ad6a-a73df110fdf8)

Platform：Ubuntu18.04
gcc version：gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
radare2 version：5.8.9
what should I do。

**Comment by trufae** [comment]
Thanks for reporting! I will fix it as soon as i can reach my laptop

**Comment by fzmili** [comment]
> I dont have any ubuntu18 (only ubuntu20 and 22) so i cant repro the problem, but i think this patch should do the job. can you try applying the patch in your r_bind.h by hand and confirm?
> 
> [radareorg/radare2#22670](https://github.com/radareorg/radare2/pull/22670)
it works

**Comment by trufae** [comment]
Closing!
