### ISSUE TITLE
Build error in anal_ghidra.cpp

### ISSUE THREAD

**Issue by Viana2021** [radareorg/r2ghidra#143]
**Describe the issue** 
I'm trying to install r2ghidra using r2pm, but some log errors appear, even though the installation continues, and when it hits 100% (after built sla) it gives gmake error.

These error messages appear in different parts of the code, so I'm pasting one of each occurrence:

/home/caio/.local/share/radare2/r2pm/git/r2ghidra-dec/src/anal_ghidra.cpp:72:7: error: ‘RAnalValue’ {aka ‘struct r_anal_value_t’} has no member named ‘type’
/home/caio/.local/share/radare2/r2pm/git/r2ghidra-dec/src/anal_ghidra.cpp:77:14: error: ‘R_ANAL_VAL_REG’ was not declared in this scope
/home/caio/.local/share/radare2/r2pm/git/r2ghidra-dec/src/anal_ghidra.cpp:82:14: error: ‘R_ANAL_VAL_MEM’ was not declared in this scope
/home/caio/.local/share/radare2/r2pm/git/r2ghidra-dec/src/anal_ghidra.cpp:126:17: error: ‘R_ANAL_VAL_IMM’ was not declared in this scope

**How to reproduce?**  
r2pm -i r2ghidra-dec

**Expected behavior**
A successful install

**Possible fix**

**Screenshots**

**Additional context**
I'm using Gentoo Linux with the latest release of radare2 (4.5.1)
I don't know if it's useful, but I'm using a version of Gentoo that does not support 32bits libs

r2 -H output:
R2_VERSION=4.5.1
R2_PREFIX=/usr
R2_MAGICPATH=/usr/share/radare2/4.5.1/magic
R2_INCDIR=/usr/include/libr
R2_LIBDIR=/usr/lib64
R2_LIBEXT=so
R2_RCONFIGHOME=/home/caio/.config/radare2
R2_RDATAHOME=/home/caio/.local/share/radare2
R2_RCACHEHOME=/home/caio/.cache/radare2
R2_LIBR_PLUGINS=/usr/lib/radare2/4.5.1
R2_USER_PLUGINS=/home/caio/.local/share/radare2/plugins
R2_USER_ZIGNS=/home/caio/.local/share/radare2/zigns

**Comment by karliss** [comment]
r2pm is probably using r2ghidra master. You either need to use r2 master or instruct r2pm to use matching r2ghidra tag.

**Comment by Viana2021** [comment]
Hii, thanks for the reply. I was using r2 4.5.1 and downgraded to 4.5.0, the error changed but the install still failing.
Now I compiled r2 from github source, and everything works fine :)
Maybe It's a problem of the Gentoo version. I'm going to call them and try to discover the issue.

I'm closing the issue since It's appear to be a problem more related to the distro. Thanks again :)
