### ISSUE TITLE
Error while trying to install with `r2pm -ci r2ghidra` command

### ISSUE THREAD

**Issue by ImJoke** [radareorg/r2ghidra#143]
Here is the error mesage
![image](https://github.com/radareorg/r2ghidra/assets/55929550/0c73593f-569a-421e-975e-e8d51494bded)

This is my kali version
![image](https://github.com/radareorg/r2ghidra/assets/55929550/0e28c551-0da8-4c11-a34f-e4295d5c4601)

**Comment by trufae** [comment]
Version of r2?

**Comment by ImJoke** [comment]
owh yeah, i just need to upgrade my r2. I forgot it...
