### ISSUE TITLE
No tag corresponding the latest radare2 release 4.5.1

### ISSUE THREAD

**Issue by Nicceboy** [radareorg/r2ghidra#151]
**Describe the issue**

Related to #92 ; latest release of radare2  was made couple weeks ago, but there is no tagged commit here to pinpoint compatibility of that release. Is it forgotten, or is there change for doing this? Or should I expect that there are no breaking changes, if no tag is being used?

**Expected behavior**

Tag commit, when r2 release was made.

**Comment by thestr4ng3r** [comment]
Thanks for the reminder, the tags exist now.
