### ISSUE TITLE
Unable to decompile any function

### ISSUE THREAD

**Issue by Talos878** [radareorg/r2ghidra#168]
After installing r2ghidra-dec using r2pm -i r2ghidra-dec and then attempting to decompile any function, I simply get the error: "Ghidra Decompiler Error: No function at this offset"

![image](https://user-images.githubusercontent.com/13156320/96662111-a3516f80-131b-11eb-894b-5cbf3949ee07.png)

The code called in this instance is in the Decompile function in core_ghidra.cpp

![image](https://user-images.githubusercontent.com/13156320/96662537-8ff2d400-131c-11eb-8ed5-587d2ac046a4.png)

After backtracking a bit, it seems that the value passed in as the first argument to r_anal_get_fcn_in is null: core->anal. A few functions down this is checked for a value true is returned here

![image](https://user-images.githubusercontent.com/13156320/96662838-5078b780-131d-11eb-9dc7-394cd51ca7d1.png)

Though this seems like a condition for failure the code returns true?
![image](https://user-images.githubusercontent.com/13156320/96662908-79994800-131d-11eb-8089-b09641b02936.png)

The return value is ignored anyways in the function above.
![image](https://user-images.githubusercontent.com/13156320/96662950-96ce1680-131d-11eb-84b6-464aeca95b85.png)

The whole backtrace goes something like:
r_anal_get_fcn_in
r_anal_get_functions_in
r_anal_blocks_foreach_in  <-- this checks if bb_tree exists and subsequently fails
all_in <-- returns true as error response

tracing back where the core argument comes from it is passed in as a void* user here:
![image](https://user-images.githubusercontent.com/13156320/96663397-9aae6880-131e-11eb-9b3d-fbb7c40828ca.png)

My best guess is something in radare2 was refactored and so core->anal->bb_tree is either nonexistent or initialized at a different time so its value is 0 when r2ghidra wants to use it.

My radare2 version:
$ r2 -v
radare2 4.6.0-git 25162 @ linux-x86-64 git.4.4.0-828-g4287408a3
commit: 4287408a3efbabcba35fe6617cf7623f515c7442 build: 2020-10-20__20:53:21

r2ghidra is on master and up to date inside r2pm's copy of the git repo
![image](https://user-images.githubusercontent.com/13156320/96663621-042e7700-131f-11eb-9e14-2604c7aceb0e.png)

As previously mentioned, I'm installing using r2pm. (I have had varied luck with the build instructions in r2ghidra-dec, r2pm installation seems more consistent but thats another story)

radare2 I'm just installing by git cloning and running sys/install.sh

on ubuntu 18
Linux --name--- 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I'll try to post more if I figure out more whats goin on.
Thanks for any help, if anyone knows whats going on.

**Comment by Talos878** [comment]
doubt this matters but I'm trying to decompile the main function of this basic test file.
![image](https://user-images.githubusercontent.com/13156320/96663909-b0705d80-131f-11eb-83e1-4217f3f4fb45.png)

g++ test.cpp -o test.out

**Comment by trufae** [comment]
Just type af. If the function is not analized it cant be decompiled

**Comment by Talos878** [comment]
lol. Thanks
