### ISSUE TITLE
XML error parsing SLEIGH file for riscv

### ISSUE THREAD

**Issue by jstaursky** [radareorg/r2ghidra#18]
**Describe the issue**

unable to emulate riscv 

**How to reproduce?**

1. install plugin `r2pm -ci r2ghidra`
2. check support for emulation `rasm2 -L` (shows `_dAe ... r2ghidra`)
3. compile a c file using 
   `riscv64-linux-gnu-gcc hello-world.c -o hello-world`
or even
   `clang --target=riscv64 -march=rv64gc -c hello-world.c (linking appears to have issues on clang)`

try to emulate

`r2 -a r2ghidra -e asm.cpu=riscv hello-world`

goto asm page

see  error
![image](https://user-images.githubusercontent.com/25406664/110497031-176e9300-80c4-11eb-9c7f-f84484d27eae.png)

**Expected behavior**

radare2 opens file and can step through assembly via ESIL

**Comment by trufae** [comment]
Cant reproduce. i tried with two riscv elf binaries and r2ghidra works as expected, disasm fine and decompiles fine. So i guess this is an issue related to your installation/setup. are you using r2 and r2ghidra from git?

**Comment by trufae** [comment]
which operating system are you using?

**Comment by jstaursky** [comment]
so uhhhh I still have the issue.
I went to my radare2 install (from git) did `make uninstall` then `make purge`. Then I `rm -rf ~/radare2` 
then
`git clone https://github.com/radareorg/radare2.git`
`cd radare2`
`sudo sys/install.sh --with-capstone5`
`r2pm -ci r2ghidra`
`r2 -a r2ghidra -e asm.cpu=riscv a.out`
same situation :/

**Comment by jstaursky** [comment]
yeah I just uninstalled capstone5 and redid the above and still running into issue. Is it the binary?

**Comment by trufae** [comment]
uhm, ubuntu 18 is pretty old.. im testing things on ubuntu20 and macOS 10.15. One reason for this failure could be the cmake build is using bison/flex to compile the xmlparser which results on this failure, the configure/make build system should work fine as its using the pregenerated C files for the xml parser. can you r2pm update and then r2pm -ci r2ghidra? (also i assume you had the last version of the r2pm package database)

I have disabled the cmake builds in the r2pm package for r2ghidra, so please try this and let me know if its working now:

```
$ r2pm up
$ r2pm -ci r2ghidra
$ r2 -a r2ghidra -e asm.cpu=riscv a.out
```


<img width="1384" alt="Screenshot 2021-03-10 at 21 12 06" src="https://user-images.githubusercontent.com/6431515/110691301-46c8f100-81e5-11eb-8ee5-0a0389f1c962.png">
...

**Comment by jstaursky** [comment]
hey I just figure out that if I don't include `-e asm.cpu=riscv` it seems to work. 
I just ran your fix and that seem to fix it (as in `-e asm.cpu=riscv` now works).
Thank you!

**Comment by jstaursky** [comment]
Oh but now quiting causes 
![image](https://user-images.githubusercontent.com/25406664/110694774-0d798c80-81b7-11eb-8225-338d5d47b5fc.png)

**Comment by trufae** [comment]
I fixed a double free in ghidra’s code. Can you run r2 with gdb and show rhe backtrace for this crash? Maybe i missed anorher global variable deinitialized twice

**Comment by jstaursky** [comment]
So I woke up and did a `make uninstall` `make purge` `make system-purge` and then reinstalled via
`sudo sys/install.sh --with-capstone5`. 
Then `r2pm init` and `r2pm -ci r2ghidra`. I noticed during the install the following
![image](https://user-images.githubusercontent.com/25406664/110798515-401f9580-8248-11eb-93ae-cc10e5553d1b.png)

and then I noticed that
![image](https://user-images.githubusercontent.com/25406664/110798681-69402600-8248-11eb-841c-1cef51212fd4.png)

heres a backtrace for doing the same thing in gdb
![image](https://user-images.githubusercontent.com/25406664/110799333-0d29d180-8249-11eb-8c60-f515ff2bccb7.png)

**Comment by trufae** [comment]
I think the problem could be related to the submodules of r2ghidra not being updated properly when r2pm -ci is called.. rimraf the r2pm/git/r2ghidra directory and run r2pm -ci again, hopeully this will fix the issue.

i fixed those double frees 1-2 months ago. its a bug in ghidra c++ code that causes double free to happen because the code is using global variables that are initialized at runtime linking time. this is fine if you load only one instance of the ghidra code in memory.. but in this case its loading it 3 times, which causes this global variable to be deinitialized 3 times and therefor a doublefree happens.

if the bug is gone after rebuilding with clean checkout ill enforce the r2pm pkg to reinitialize the submodules everytime. it will be safer :) 

thanks for the testing!

**Comment by jstaursky** [comment]
I'll have to give it another go tomorrow, have thesis defense tomorrow so cramming to put some slides together. Thanks for the help so far tho.

**Comment by trufae** [comment]
Good luck with the presentation!

**Comment by jstaursky** [comment]
Good news! I passed, but also  I have tried the above on my laptop (uninstall, purge, reinstall) and appear to be having no issues. I think something is wrong with my desktop install and I was planning on reformatting soon anyway so i'll close the issue. Thanks for all the help with the issue.

**Comment by jstaursky** [comment]
btw laptop is also running `ubuntu 18.04`

**Comment by trufae** [comment]
Awesome! Thanks for reporting!!
