### ISSUE TITLE
r2ghidra "No languages available..."

### ISSUE THREAD

**Issue by diabolist** [radareorg/r2ghidra#21]
With radare2 fresh compile from git source on Ubuntu 20.04.2 LTS and installing r2ghidra the recommended way... (`$ r2pm -ci r2ghidra`):

using `pdg` returns "Ghidra Decompiler Error: No print languages registered" 

and running `pdgs` returns "No languages available, make sure r2ghidra.sleighhome is set correctly!"

Now I have not done much research on Ghidra yet, but although the README specifically says that this is standalone, something tells me that I am missing files from Ghidra. Have I misunderstood the README for r2ghidra and expected to already have Ghidra set up?

Thanks.

**Comment by trufae** [comment]
Let me try this in the CI, it works fine for me but i think there should be an incompatibility in the build/install depending on the system

**Comment by EtchProject** [comment]
I am also having the same issue

**Comment by trufae** [comment]
Can you try updating the database and running it again?

```
r2pm up
r2pm -ci r2ghidra
```

**Comment by diabolist** [comment]
Sure. So it complained about missing cmake this time. Grabbed cmake and now it fails to build target sla. So we are getting somewhere.

"/home/rdh/.local/share/radare2/r2pm/git/r2ghidra/src/SleighInstruction.h:13:10: fatal error: R2LoadImage.h: No such file or directory"

And here is the build log:
https://pastebin.com/ZH9Ciyfe

Thanks.

**Comment by EtchProject** [comment]
Tried updating and running again. Noticed there were errors this time

```
fatal error: R2LoadImage.h: No such file or directory
```

Not sure if you get the same thing @diabolist

**Comment by hitxieming** [comment]
I also have this thing ,@EtchProject

**Comment by diabolist** [comment]
I tried building from source using cmake.

In file `src/SleighInstruction.h` R2LoadImage.h is included as a system header file so including it in quotes fixed the fail. I tried pushing the fix but I do not have the permission.

Anyways, after building and installing I still have the same issue.

The `*.sla` files (and others) are located in `~/.local/lib/radare2/last/r2ghidra_sleigh/`.

**Comment by trufae** [comment]
Try again :) both issues should be fixed now

**Comment by EtchProject** [comment]
Works. Thanks

**Comment by diabolist** [comment]
@trufae, working as expected, tyvm!

**Comment by trufae** [comment]
Yay ! thanks for confirming the fix!
