### ISSUE TITLE
option to do pdg with <timeout>

### ISSUE THREAD

**Issue by ca-raf** [radareorg/r2ghidra#23]
Adding a timeout for pdg instruction (Decompile current function with Ghidra decompiler).

I fixed this issue locally for my linux os environment Adding pdgt <timeout> command that decompile function until timeout.

And changing _cmd function in core_ghidra.cpp as follows:

static int e_child_pid = 0;
static void timer_handler(int pid) 
{
  kill(e_child_pid, SIGKILL);
}

static void _cmd(RCore *core, const char *input)
{
	switch(*input)
	{
		case 'd': // "pdgd"
			DecompileCmd(core, DecompileMode::DEBUG_XML);
			break;
		case '\0': // "pdg"
			DecompileCmd(core, DecompileMode::DEFAULT);
			break;
		case 't': // "pdgt"
                {
                        ut64 timeout = (ut64)strtoull(input + 2, nullptr, 0);
                        signal(SIGALRM, timer_handler);
                        pid_t pid = fork();
                        e_child_pid = pid;
                        if (pid < 0) {
                        	eprintf("Fork failed!\n");
                        }
                        if (pid == 0) {
				DecompileCmd(core, DecompileMode::DEFAULT);
			} else {
			        alarm(timeout);
			        int state;
			        waitpid(pid, &state, 0);
			}
			break;
                }
		case 'x': // "pdgx"
			DecompileCmd(core, DecompileMode::XML);
			break;
		case 'j': // "pdgj"
			DecompileCmd(core, DecompileMode::JSON);
			break;
		case 'o': // "pdgo"
			DecompileCmd(core, DecompileMode::OFFSET);
			break;
		case '*': // "pdg*"
			DecompileCmd(core, DecompileMode::STATEMENTS);
			break;
		case 's': // "pdgs"
			switch(input[1])
			{
				case 's': // "pdgss"
					PrintAutoSleighLang(core);
					break;
				case 'd': // "pdgsd"
					Disassemble(core, (ut64)strtoull(input + 2, nullptr, 0));
					break;
				default:
					ListSleighLangs();
					break;
			}
			break;
		case 'a': // "pdga"
			EnablePlugin(core);
			break;
		default:
			PrintUsage(core);
			break;
	}
}

**Comment by trufae** [comment]
Can you submit a PR for better discussing it there? Some comments below:

* Use r_sys_fork() to make this fork() portable and honor the sandbox (its unix specific)
* Move the code into a separate function
* I dont think adding a timeout as a new command is ideal, better add an r2ghidra.timeout eval variable
* Can you handle ^C in here too?
* When the timeout is 0 it should just call normally without the fork+signal thing

**Comment by trufae** [comment]
ping?

**Comment by ca-raf** [comment]
Hi,

I attach to this mail the final version i am using to add timeout to pdg.

As you can see in the attached file I didn't address most of your request
regarding improvements:

   -   I still have pdgt instruction rather than a radare2 variable.

Moreover I made another change that I don't think you will approve.
I changed the pdgt prints from r_core_annotated_code_print to console
fprintf. This causes the prints to be less human readable with no colors.
The reason I did this modification is that it seems that i get a memory
leak in the previous mentioned version.
The only way to solve this problem was to ensure the child thread exit. But
on child exit, output of the child thread will not be displayed if you rely
on r_core_annotated_code_print [which prints just on a clean return] just
on fprintf.

I use this version and I am happy with the results but as I understand this
version does not meet commits standards.

**Comment by trufae** [comment]
What do you users think about this feature? Its hacky but may be useful in some situations. Mainly on user interfaces. Running it as a task could be a cleaner the solution
