### ISSUE TITLE
install error with r2pm

### ISSUE THREAD

**Issue by ArcticSpaceFox** [radareorg/r2ghidra#28]
**Describe the issue**

trying to install with `r2pm` fails for me. 

![image](https://user-images.githubusercontent.com/36639589/115117805-e4a39e80-9f8f-11eb-9b81-2db47c4074ab.png)

**How to reproduce?**

Idk install it via `r2pm`

**Expected behavior**

a successful install

**Additional context**
![image](https://user-images.githubusercontent.com/36639589/115118028-e5890000-9f90-11eb-9515-8a264b5558ee.png)

**Comment by trufae** [comment]
The error message is not in the screenshot. Its probably failing some lines above. My blind guess is that its failing to compile because you are using an old version of r2. Latest r2ghidra needs r2-5.2 because of api/abi changes

**Comment by ArcticSpaceFox** [comment]
yep youre a genious x_x
