### ISSUE TITLE
r2pm -ci r2ghidra fails on /usr/bin/cc on linux mint 20.1

### ISSUE THREAD

**Issue by linxcow** [radareorg/r2ghidra#30]
I have installed r2 from deb release 5.2.1 no problems

sudo apt install cmake

r2pm -ci r2ghidra

Cleaning r2ghidra...
clean Done For r2ghidra
/home/mint/.local/share/radare2/r2pm/db/r2ghidra TGZ=
Cleaning up /home/mint/.local/share/radare2/r2pm/git/r2ghidra...
Cloning into 'r2ghidra'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 103 (delta 1), reused 49 (delta 1), pack-reused 0
Receiving objects: 100% (103/103), 265.45 KiB | 2.19 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Submodule 'ghidra/ghidra' (https://github.com/radareorg/ghidra.git) registered for path 'ghidra/ghidra'
Submodule 'third-party/pugixml' (https://github.com/zeux/pugixml.git) registered for path 'third-party/pugixml'
Cloning into '/home/mint/.local/share/radare2/r2pm/git/r2ghidra/ghidra/ghidra'...
remote: Enumerating objects: 98154, done.
remote: Total 98154 (delta 0), reused 0 (delta 0), pack-reused 98154
Receiving objects: 100% (98154/98154), 120.51 MiB | 7.50 MiB/s, done.
Resolving deltas: 100% (60152/60152), done.
Cloning into '/home/mint/.local/share/radare2/r2pm/git/r2ghidra/third-party/pugixml'...
remote: Enumerating objects: 8880, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 8880 (delta 24), reused 26 (delta 13), pack-reused 8833
Receiving objects: 100% (8880/8880), 6.31 MiB | 4.57 MiB/s, done.
Resolving deltas: 100% (6121/6121), done.
Submodule path 'ghidra/ghidra': checked out '5560ac1711a07705e8fdb232726593f957d6dd5a'
Submodule path 'third-party/pugixml': checked out '0e3f1699ffab5f820060fe99c61f0f9495c0c5b6'
error: pathspec 'r2-5.2.1' did not match any file(s) known to git
Already up to date.
Install Done For r2ghidra
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
The C compiler

"/usr/bin/cc"

is not able to compile a simple test program.

It fails with the following output:

Change Dir: /home/mint/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_66298/fast && make -f CMakeFiles/cmTC_66298.dir/build.make CMakeFiles/cmTC_66298.dir/build
make[1]: Entering directory '/home/mint/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_66298.dir/testCCompiler.c.o
/usr/bin/cc -I/home/mint/.local/share/radare2/prefix/include -o CMakeFiles/cmTC_66298.dir/testCCompiler.c.o -c /home/mint/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_66298
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_66298.dir/link.txt --verbose=1
/usr/bin/cc -I/home/mint/.local/share/radare2/prefix/include -L/home/mint/.local/share/radare2/prefix/lib -rdynamic CMakeFiles/cmTC_66298.dir/testCCompiler.c.o -o cmTC_66298
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_66298.dir/build.make:87: cmTC_66298] Error 1
make[1]: Leaving directory '/home/mint/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_66298/fast] Error 2

CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
CMakeLists.txt:4 (project)

**Comment by trufae** [comment]
The error is quite clear: “ The C compiler "/usr/bin/cc"is not able to compile a simple test program.”

so you dont have a compiler or any of their basic dependencies/libraries like libgcc or libc. You may need to install 

according to google the pkg name you have to install is named “build-essential”.

also, theres a deb pkg for the r2ghidra decompiler in the release page iirc. You can also install it from there (hasnt been tested)

also if u installed r2-5.2.1 from the rwlease page of r2 you will need the -dev one too

**Comment by linxcow** [comment]
Thx for your help , the problem was not the compiler it seems , but not having installed the dev deb package.
I have removed all versions and dependencies from my installation and reinstalled the r2 5.2.1 versions (with dev package)

after doing the r2pm -ci r2ghidra i still get following errors : 

Module version mismatch /home/dirk/.local/share/radare2/plugins/core_pdd.so (4.2.1) vs (5.2.1)
Module version mismatch /home/dirk/.local/share/radare2/plugins/core_pdd.so (4.2.1) vs (5.2.1)

**Comment by trufae** [comment]
Those are warnings. Not errors. And it can he fixed by recompiling the r2dec plugin. r2pm -ci r2dec

**Comment by linxcow** [comment]
it worked thank you
