### ISSUE TITLE
r2pm -ci 

### ISSUE THREAD

**Issue by Ret2plt** [radareorg/r2ghidra#31]
Hello, r2pm -ci r2ghidra command, isn't actually working as it seems, it'll falsely install and not allow me to properly use r2ghidra, is there any way I can fix this?

**Comment by trufae** [comment]
Can you provide some more details on this? Which commands did you used? Operating system? Version of r2?

**Comment by trufae** [comment]
Works for me

**Comment by Ret2plt** [comment]
okay so, im sorry I didn't see this, and sorry im bad at asking questions, but it only seems to work on arch based operating systems, it was something to do with cmake command

**Comment by radare** [comment]
Try r2pm update and the r2pm -ci r2ghidra. If this doesnt work please provide output of r2 -v and compile error
