### ISSUE TITLE
Cannot build r2ghidra for Windows.

### ISSUE THREAD

**Issue by unabomber78** [radareorg/r2ghidra#49]
Cannot build r2ghidra for Windows. I had to replace Enterprise with Community in the path to the vcvarsall.bat file in preconfigure.bat for this to work on my system. But at startup configure.bat I get such output:

C:\Users\User\.local\share\radare2\r2pm\git\r2ghidra>configure.bat
"Configuring the build directory with cmake"
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc.exe
-- Check for working C compiler: /usr/bin/cc.exe - broken
CMake Error at /usr/share/cmake-3.21.3/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /c/Users/User/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/c/Python39/Scripts/ninja.exe cmTC_2f3ac && ninja: error: '/c/Users/User/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeTmp/testCCompiler.c', needed by 'CMakeFiles/cmTC_2f3ac.dir/testCCompiler.c.o', missing and no known rule to make it

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "/c/Users/User/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeOutput.log".
See also "/c/Users/User/.local/share/radare2/r2pm/git/r2ghidra/build/CMakeFiles/CMakeError.log".

**Comment by trufae** [comment]
On windows only msvc is supported for now

**Comment by trufae** [comment]
Please run the same commands as the ci

preconfigure
Configure
Make

**Comment by trufae** [comment]
Should be fixed
