### ISSUE TITLE
No sleigh specification for PowerPC:BE:32:default

### ISSUE THREAD

**Issue by stupidestmodder** [radareorg/r2ghidra#57]
OS: Android-Termux

i installed r2ghidra using those commands
`r2pm update`
`r2pm -i r2ghidra`
it then downloaded, compiled and installed everything, but when a try and actually use it it says this `Ghidra Decompiler Error: No sleigh specification for PowerPC:BE:32:default`
what can i do to fix this
thxs

**Comment by trufae** [comment]
Are you trying to decompile a ppc binary?

i would recommend you to install the r2ghidra and r2ghidra-sleigh packages using -ci instead of just -i to ensure a clean build

**Comment by stupidestmodder** [comment]
> Are you trying to decompile a ppc binary?
yeah
> i would recommend you to install the r2ghidra and r2ghidra-sleigh packages using -ci instead of just -i to ensure a clean build
aight gonna try that

**Comment by stupidestmodder** [comment]
still the same error :(

**Comment by trufae** [comment]
Powerpc support wasnt added in the default build. So i assume you are trying to decompile a powerpc binary in termux. Right?

i uploaded a separate zip in the release page with all the archs precompiled. You can download it and unzip it in your r2 plugin dir, in the r2ghidra_sleigh directory.

i may probably do a new release to ship them by default

**Comment by stupidestmodder** [comment]
so i did that, downloaded the zip, extracted it into the plugins folder and now im getting another error when trying to decompile (powerpc binary) `Ghidra Decompiler Error: Symbol arg_1h extends beyond the end of the address space`

aarch64 works, just powerpc that doesn't want to cooperate
:/

**Comment by trufae** [comment]
Can you share the binary or point me to a binary from the r2 testsuite to verify?

**Comment by stupidestmodder** [comment]
alright I'll close this issue as that is fixed and we can talk more on discord
