### ISSUE TITLE
BUG: Ghidra Decompiler Error: No print languages registered

### ISSUE THREAD

**Issue by srobertjames** [radareorg/r2ghidra#61]
I recently cleaned out and fresh installed radare2, and now get this error:

```
[0x00001060]> s main
[0x00001159]> pdg
Ghidra Decompiler Error: No print languages registered
```

I tried with multiple binaries.  r2 installed from git:
```
$ r2pm -l
r2book
r2frida
r2ghidra
r2ghidra-sleigh

$ r2 -V
5.5.4  r2
5.5.4  r_anal
5.5.4  r_lib
5.5.4  r_egg
5.5.4  r_asm
5.5.4  r_bin
5.5.4  r_cons
5.5.4  r_flag
5.5.4  r_core
5.5.4  r_crypto
5.5.4  r_bp
5.5.4  r_debug
5.5.4  r_main
5.5.4  r_hash
5.5.4  r_fs
5.5.4  r_io
5.5.4  r_magic
5.5.4  r_parse
5.5.4  r_reg
5.5.4  r_sign
5.5.4  r_search
5.5.4  r_syscall
5.5.4  r_util

~/tmp/radare2$ git log | head
commit 6231e6058513be306f34fb29132441d8235e7114
Author: pancake <pancake@nowsecure.com>
Date:   Tue Feb 1 20:03:26 2022 +0100

    Fix #18621 - Specify ABI version to be X.Y instead of X.Y.Z ##build
    
    * Installation creates some more symlinks now

```

**Comment by srobertjames** [comment]
Can you comment on this? If for some reason you consider this a non-issue, please state so (and why).

**Comment by trufae** [comment]
I cant repro and i tried on mac and linux on latest git and previous build too. 

Can you confirm you did

r2pm -ci r2ghidra
r2pm -ci r2ghidra-sleigh

?

**Comment by srobertjames** [comment]
Thank you, the "-ci" fixed it.  The only thing I can think that caused it is that I first installed r2ghidra (and other plugins), tried running it, then installed r2ghidra-sleigh.  Perhaps splitting them (with other plugins in between) broke something.
