### ISSUE TITLE
5.6.4 release

### ISSUE THREAD

**Issue by kimstik** [radareorg/r2ghidra#64]
May we expect binaries of subj?

**Comment by trufae** [comment]
Sure i would like to get the automated artifact publication in the release cycle also for r2ghidra. ill push the last artifacts from the CI. also, bear in mind that r2 is now abi-stable if majhor and minor versions m atch. so you can use r2-5.6.x with any build of r2ghidra-5.6.x. no need to match the exact numbers.

ill close the ticket when i do that

**Comment by trufae** [comment]
I'll focus to target 5.7 for the automated release builds of r2ghidra
