### ISSUE TITLE
error: 'RAnal'

### ISSUE THREAD

**Issue by Envincion** [radareorg/r2ghidra#66]
im trying to install r2ghidra so i can be able to 'pdg' in radare2 ,i tried to install it with `r2pm -ci r2ghidra`
i had error with r_core ,after long research ,i found out installing libxxhash-dev can solve this issue and it did.
now im stuck with another error ,i have no clue how to pass this ,please help.

![image](https://user-images.githubusercontent.com/50993067/166200433-63dce787-00f4-46da-b0d9-74b329091cbb.png)

**Comment by trufae** [comment]
If you are using r2 from git you need to use r2ghidra from git
