### ISSUE TITLE
[BUG] Windows Build Errors

### ISSUE THREAD

**Issue by CypherpunkSamurai** [radareorg/r2ghidra#67]
# [BUG] Windows Build Errors
## **Issue Description:**
The batch scripts provided to configure and make the plugin seem to have errors. Also the plugin sources have errors, which is causing ninja to teminate abruptly, but the CI continues without detecting. Windows builds have the following errors that i have spotted till now.

## **Issue Causes and Solutions (if any spotted):**
Firstly the preconfigure scripts have 2 errors.

- [x] ~The ARCH variable is declared but later left unused [L18](https://github.com/radareorg/r2ghidra/blob/bb152cb87424630d96e971696f9c3ee92990f88d/preconfigure.bat#L18).~

  ~**First Solution:**~
  ~I fixed this little bug by replacing `%VSARCH%` with `%ARCH%`~
  ~```bash~
  ~sed -i 's|%VSARCH%|%ARCH%|g' preconfigure.bat~
  ~```~

  **Fixed in commit fd5366d**
- [ ] Secondly the url provided for ghidra-native is broken [L6](https://github.com/radareorg/r2ghidra/blob/bb152cb87424630d96e971696f9c3ee92990f88d/preconfigure.bat#L6).
  **Second Solution:**
  To fix this I replaced the url with tag url
  ```diff
  - python -m wget https://github.com/radareorg/ghidra-native/releases/download/0.1.8/ghidra-native-0.1.8.zip
  + python -m wget https://github.com/radareorg/ghidra-native/archive/refs/tags/0.1.8.zip -o ghidra-native-0.1.8.zip
- [ ] Errors in `src\CodeXMLParse.cpp` cause plugin dll build to fail. [\[Logs Here\]](https://github.com/CypherpunkSamurai/r2ghidra/runs/6343369764?check_suite_focus=true#step:7:144).
- [ ] Errors in `src\ArchMap.cpp` cause plugin sleigh build to fail. [\[Logs Here\]](https://github.com/CypherpunkSamurai/r2ghidra/runs/6343369764?check_suite_focus=true#step:8:93).

## Related Issues
None spotted till now.

**Comment by trufae** [comment]
The other 3 points are wrong. 

I didnt created the release with the tag, so the 0.1.8 artifact wasnt generated. this dist zip contains the patched source. otherwise you get the compile errors if you pick the src directly from git.

ill close this ticket now when i get the thing to compile

**Comment by trufae** [comment]
All fixed. Thanks for motivating me to do it
