### ISSUE TITLE
Ghidra Decompiler Error: parameter list floating-point entries must come first

### ISSUE THREAD

**Issue by andrewathalye** [radareorg/r2ghidra#78]
I am attempting to decompile a .NET native x86_64 Windows DLL on Linux using Radare2 5.6.8 and the latest version of r2ghidra.

When I try to decompile any function, I am greeted with "Ghidra Decompiler Error: parameter list floating-point entries must come first," with no other information.

I am able to decompile Linux x86_64 binaries without issue, as well as use pdd from r2dec to decompile the same DLL's functions.

**Comment by trufae** [comment]
i can reproduce this with the 'arg' binary that is commited in the repo, and this error comes from the x86-64 sleigh definition. i just took the x86 precompiled files from the 5.7.2 release and patched the package and its working again. i will do a new release of ghidra-native with the old sleigh files to ensure this is works for non-precompiled installations.

you can update the r2ghidra-sleigh package to experience the fix

**Comment by trufae** [comment]
https://github.com/radareorg/r2ghidra/runs/7361125845?check_suite_focus=true#step:9:3845
