### ISSUE TITLE
r2ghidra 5.7.6 r_asm_t->config compile error against radare 5.7.6

### ISSUE THREAD

**Issue by anthraxx** [radareorg/r2ghidra#91]
latest r2ghidra 5.7.6 seems to have an API incompatibility to radare 5.7.6 :crying_cat_face: 

```
../src/R2LoadImage.cpp: In lambda function:
../src/R2LoadImage.cpp:67:64: error: ‘RAsm’ {aka ‘struct r_asm_t’} has no member named ‘config’
   67 |                                         int inc = (core->rasm->config->bits == 64)? 8: 4;
      |                                                                ^~~~~~
```

**Comment by trufae** [comment]
This was introduced in 5.7.0, so it must be there unless its linking to an old version

**Comment by anthraxx** [comment]
The only version inside the build chroot is `radare2 5.7.6 0 @ linux-x86-64 git.5.7.6`. :man_shrugging:

**Comment by anthraxx** [comment]
Ok the issue was not inside the chroot but outside, the build log file was not updated duo to an issue hence this message was from some lot earlier run.
